sonar.projectKey=meyer-pidiache_keychat
sonar.organization=meyer-pidiache
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/node_modules/**,web/dist/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=web/**

sonar.go.coverage.reportPaths=coverage.out

sonar.typescript.tsconfigPath=web/tsconfig.json

sonar.sourceEncoding=UTF-8
