sonar.projectKey=meyer-pidiache_keychat
sonar.organization=meyer-pidiache
sonar.host.url=https://sonarcloud.io

sonar.sources=.,web/src
sonar.exclusions=**/*_test.go,**/node_modules/**,web/dist/**

sonar.tests=.,web
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.typescript.tsconfigPath=web/tsconfig.json

sonar.sourceEncoding=UTF-8
